ARG PYTHON_V=3.7
ARG AIRFLOW_V=2.1.2

FROM python:$PYTHON_V

ENV AIRFLOW_HOME=/
ENV AIRFLOW_VERSION=$AIRFLOW_V
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False

WORKDIR ${AIRFLOW_HOME}

COPY ./script/ ./script/
RUN . ./script/setup.sh

CMD ["python", "script/start.py"]
