ARG PYTHON_V=3.7
ARG AIRFLOW_V=2.1.2

FROM python:$PYTHON_V

ENV AIRFLOW_HOME=/
ENV AIRFLOW_VERSION=$AIRFLOW_V
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False

WORKDIR ${AIRFLOW_HOME}

COPY ./script/ .
RUN . ./setup.sh

CMD ["python", "start.py"]
