name: CI Build

on:
  push:
    branches:
      - 'master'
    paths:
      - 'image/**'

concurrency:
  group: docker-hub
  cancel-in-progress: true


jobs:
  params:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
    - id: set-matrix
      run: |
        content=`cat ./image/config.json`
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=matrix::$content"

  docker:
    name: "Push to Docker HUB"
    needs: params
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.params.outputs.matrix)}}
    steps:
      - run: echo ${{matrix.python}} ${{matrix.airflow}}
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/airflow:${{matrix.airflow}}-py${{matrix.python}} \
            --build-arg PYTHON_V=${{matrix.python}} \
            --build-arg AIRFLOW_VERSION='${{matrix.airflow}}' \
            --no-cache .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/airflow:${{matrix.airflow}}-py${{matrix.python}}
        working-directory: image
