name: ci

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - image/**

jobs:
  params:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        JSON=$(cat ./image/config.json)
        echo "::set-output name=matrix::${JSON//'%'/'%25'}"

  docker:
    needs: params
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.params.outputs.matrix)}}
    steps:
      - run: echo ${{matrix.python}} ${{matrix.airflow}}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: image
          push: true
          tags: user/app:latest
          build-args: 
